name: Django Backend Build & Test Workflow (Dev)
on:
  push:
    branches: ["main", "dev/**"]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        working-directory: ./services/backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run docker compose
      run: docker compose -f docker-compose.dev.yml up -d